import assert from 'node:assert/strict';
import fs from 'node:fs';
import {calculatedStats,updatedCarrySize} from '../dist/pokemon-stats.js';
import {Engine} from '../dist/engine.js';
const catalog=JSON.parse(fs.readFileSync(new URL('../dist/catalog.json',import.meta.url)));
const treecko={species:'TREECKO',level:13,nature:'Impish',carrySize:8,subskills:['Berry Finding S','Inventory Up M','Skill Trigger S','Inventory Up S','Skill Level Up S']};
assert.deepEqual(calculatedStats(catalog,treecko),{frequencySeconds:4392,carrySize:8});
const grovyle={...treecko,species:'GROVYLE'},sceptile={...treecko,species:'SCEPTILE'};
assert.deepEqual(calculatedStats(catalog,grovyle),{frequencySeconds:3220,carrySize:16});
assert.equal(updatedCarrySize(catalog,grovyle,treecko),16);
assert.equal(updatedCarrySize(catalog,sceptile,treecko),27);
assert.equal(updatedCarrySize(catalog,{...sceptile,level:25},treecko),39);
assert.equal(updatedCarrySize(catalog,treecko,{...grovyle,carrySize:16}),8);
const gardevoir={species:'GARDEVOIR',level:52,nature:'Gentle',carrySize:29,subskills:['Ingredient Finder M','Helping Speed M','Skill Trigger M','Inventory Up S','Skill Trigger S']};
assert.deepEqual(calculatedStats(catalog,gardevoir),{frequencySeconds:1853,carrySize:28});
assert.equal(updatedCarrySize(catalog,{...gardevoir,species:'KIRLIA'},gardevoir),19,'Preserve one extra carry slot');
assert.equal(updatedCarrySize(catalog,{...gardevoir,level:70},gardevoir),35,'Unlock Inventory Up without double-counting existing extras');
assert.equal(updatedCarrySize(catalog,{...gardevoir,level:70,subskills:[...gardevoir.subskills.slice(0,3),'Inventory Up M','Skill Trigger S']},gardevoir),41);
assert.equal(updatedCarrySize(catalog,gardevoir,gardevoir),29,'Returning to the original build restores its carry limit');
assert.equal(updatedCarrySize(catalog,treecko,gardevoir),8,'New unrelated species must not inherit other Pokémon bonuses');
assert.equal(calculatedStats(catalog,{...treecko,species:'DRATINI',level:14,nature:'Brave'}).frequencySeconds,4383);
const own={...gardevoir,subskills:['Helping Bonus','Helping Speed M','Skill Trigger M','',''],settings:{teamHelpingBonus:4,energyMultiplier:2.5}};
assert.equal(calculatedStats(catalog,own).frequencySeconds,1853,'Detail-screen frequency excludes team bonuses and energy');
for(const partial of [{...treecko,species:''},{...treecko,level:0},{...treecko,level:25.5}])assert.deepEqual(calculatedStats(catalog,partial),{frequencySeconds:null,carrySize:null});
assert.deepEqual(calculatedStats(catalog,{...treecko,nature:''}),{frequencySeconds:null,carrySize:8});
for(const p of catalog.species){
 const b={...treecko,species:p.name,level:1,subskills:['','','','','']},s=calculatedStats(catalog,b);
 assert.equal(s.frequencySeconds,p.frequency,p.name);
 assert.equal(s.carrySize,p.carrySize+5*p.previousEvolutions,p.name);
}
const build={...gardevoir,skillLevel:6,ingredients:['Apple','Apple','Apple'],displayedFrequencySeconds:1853,frequencySource:'calculated'};
const engine=new Engine(catalog);
assert.equal(engine.validate(build).frequencySource,'calculated');
assert.throws(()=>engine.validate({...build,frequencySource:'unknown'}));
await import(process.argv[2]);globalThis.fetch=async()=>new Response(JSON.stringify(catalog));
const {api,database}=await import('../dist/local-api.js');
const row=await api('/api/pokemon',{method:'POST',body:JSON.stringify({build})});
const saved=await api('/api/pokemon/'+row.id);
assert.equal(saved.analysis.build.frequencySource,'calculated');
assert.equal(saved.analysis.build.carrySize,29);
const backup=await api('/api/backup');
assert.equal(backup.pokemon[0].build.frequencySource,'calculated');
const restoredId=crypto.randomUUID();
await api('/api/restore',{method:'POST',body:JSON.stringify({...backup,pokemon:[{...backup.pokemon[0],id:restoredId}]})});
assert.deepEqual((await api('/api/pokemon/'+row.id)).analysis.build,saved.analysis.build);
assert.equal((await api('/api/pokemon')).length,1,'Compatible cross-ID restore retains the saved identity');
(await database()).close();
console.log('Passed: 249 species base stats, evolution bonuses, active subskills, preserved carry extras, independent own frequency, partial forms, source validation and backup round-trip.');
