import fs from 'node:fs';
import assert from 'node:assert/strict';
import {Engine} from '../dist/engine.js';
import {parseOCR} from '../dist/ocr-parser.js';
import {calculatedStats} from '../dist/pokemon-stats.js';
import {speciesChoices} from '../dist/evolution.js';
import {portraitRegion,rankSprites,confidentSpriteMatch,confidentMatch} from '../dist/sprite-matcher.js';
import {ingredientRegions,resolveIngredients} from '../dist/ingredient-matcher.js';
const read=path=>JSON.parse(fs.readFileSync(new URL(path,import.meta.url)));
const c=read('../dist/catalog.json'),mac=read('../../catalog/pokemon.json'),fixture=read('foongus-regression.json');
assert.equal(c.commit,'74e5068c1fa76518803caa8705798389da7f635d');
assert.equal(c.commit,mac.commit);
assert.deepEqual(c.species,mac.species);
const fields=parseOCR([{lines:fixture.lines}],c).fields;
assert.deepEqual(fields,{species:'FOONGUS',nature:'Hasty',level:14,skillLevel:1,carrySize:12,subskills:['Skill Trigger S','Inventory Up S','Ingredient Finder S','Energy Recovery Bonus','Ingredient Finder M'],displayedFrequencySeconds:5551});
const refs=read('../dist/sprite-features.json'),ingredients=read('../dist/ingredient-features.json');
const bytes=base64=>Uint8Array.from(Buffer.from(base64,'base64'));
assert.deepEqual(portraitRegion(fixture.lines,fixture.width,fixture.height),fixture.portrait.region);
assert.equal(confidentSpriteMatch(rankSprites(bytes(fixture.portrait.pixels),refs.entries)),'FOONGUS');
assert.deepEqual(ingredientRegions(fixture.lines,fixture.width,fixture.height),fixture.slots.map(s=>s.region));
const hits=fixture.slots.map(s=>{const candidates=rankSprites(bytes(s.pixels),ingredients.entries);return {...s.region,candidates,ingredient:confidentMatch(candidates)}});
const foongus=c.species.find(p=>p.name==='FOONGUS'),amoonguss=c.species.find(p=>p.name==='AMOONGUSS');
assert.deepEqual(resolveIngredients(hits,foongus).ingredients,['','Mushroom','Mushroom']);
assert.deepEqual([foongus.frequency,foongus.carrySize,foongus.ingredientPercentage,foongus.skillPercentage],[5700,12,17.4,3.5]);
assert.deepEqual([amoonguss.frequency,amoonguss.carrySize,amoonguss.ingredientPercentage,amoonguss.skillPercentage],[3500,14,20.4,4.7]);
for(const p of [foongus,amoonguss]){
  assert.equal(p.specialty,'ingredient');assert.equal(p.berry.name,'CHESTO');
  assert.equal(p.skillLabel,'Charge Strength S');assert.equal(p.skill.strengthAmounts[0],400);
  assert.deepEqual([0,30,60].map(level=>p[`ingredient${level}`].map(s=>[s.ingredient.name,s.amount])),[[['Mushroom',2]],[['Mushroom',5],['Egg',7]],[['Mushroom',7],['Egg',10],['Tomato',11]]]);
  for(const shiny of [false,true])assert.equal(refs.entries.filter(e=>e.species===p.name&&e.shiny===shiny).length,3);
}
assert.deepEqual(speciesChoices(c,'FOONGUS').map(p=>p.name).sort(),['AMOONGUSS','FOONGUS']);
const engine=new Engine(c),build=engine.validate({...fields,ingredients:['Mushroom','Mushroom','Mushroom'],settings:c.defaults});
assert.deepEqual(calculatedStats(c,build),{frequencySeconds:5551,carrySize:12});
assert.equal(calculatedStats(c,{...build,species:'AMOONGUSS'}).carrySize,19);
const result=engine.analyze(build);
assert.equal(result.catalogCommit,c.commit);assert.ok(result.current.strength>0);
assert.ok(result.current.ingredients.find(i=>i.name==='Mushroom').count>0);
assert.deepEqual(result.forecasts.map(f=>f.level),[30,60,70,80]);
console.log('Passed: Foongus screenshot text, portrait, locked mushrooms, subskills, own frequency/carry, source stats, evolution, calculation and catalog parity.');
