import assert from 'node:assert/strict';
import {collectionRows,specialtyCounts} from '../dist/collection.js';
const catalog=[{name:'GARDEVOIR',displayName:'Gardevoir',specialty:'skill'},{name:'RAICHU',displayName:'Raichu',specialty:'berry'},{name:'CHARIZARD',displayName:'Charizard',specialty:'ingredient'},{name:'MEW',displayName:'Mew',specialty:'all'}];
const records=catalog.map((p,i)=>({id:p.name,analysis:{build:{species:p.name,nickname:i===0?'医生':p.displayName,level:50-i},current:{strength:100+i,skillTriggers:4.25,ingredientCount:30.5,berryCount:80.5,ratings:{strength:90}}}}));
const ids=options=>collectionRows(records,catalog,options).map(r=>r.id);
assert.deepEqual(ids({prefix:'  gArD '}),['GARDEVOIR']);
assert.deepEqual(ids({prefix:'医'}),['GARDEVOIR']);
assert.deepEqual(ids({prefix:'chu'}),[],'Suffixes must not match a name-prefix filter');
assert.deepEqual(ids({prefix:'CHAR',specialty:'ingredient'}),['CHARIZARD']);
assert.deepEqual(ids({prefix:'CHAR',specialty:'skill'}),[]);
assert.deepEqual(ids({specialty:'all'}),['MEW']);
assert.deepEqual(ids({sort:'strength'}),['MEW','CHARIZARD','RAICHU','GARDEVOIR']);
assert.deepEqual(ids({sort:'level'}),['GARDEVOIR','RAICHU','CHARIZARD','MEW']);
assert.deepEqual(records.map(r=>r.id),catalog.map(p=>p.name),'Filtering and sorting must not change stored record order');
const current=records[0].analysis.current;
assert.deepEqual(specialtyCounts(current,'skill').map(x=>[x.label,x.value]),[['skill triggers',4.25]]);
assert.deepEqual(specialtyCounts(current,'ingredient').map(x=>[x.label,x.value]),[['ingredients',30.5]]);
assert.deepEqual(specialtyCounts(current,'berry').map(x=>[x.label,x.value]),[['berries',80.5]]);
assert.equal(specialtyCounts(current,'all').length,3);
assert.deepEqual(ids({prefix:'nothing'}),[]);
console.log('Passed: nickname/species prefixes, case and whitespace, Chinese names, combined specialty filters, all-rounders, metric selection, and sorting without mutating records.');
