import assert from 'node:assert/strict';
import fs from 'node:fs';
import {matchesProgression} from '../dist/build-identity.js';
await import(process.argv[2]);
const catalog=JSON.parse(fs.readFileSync(new URL('../dist/catalog.json',import.meta.url)));
globalThis.fetch=async()=>new Response(JSON.stringify(catalog));
const {api,database,savePictures}=await import('../dist/local-api.js');
const post=(path,body)=>api(path,{method:'POST',body:JSON.stringify(body)});
const base={species:'RAICHU',nickname:'Sparky',level:20,nature:'Hardy',skillLevel:3,carrySize:31,subskills:['Skill Trigger S','Helping Speed S','Ingredient Finder S','Inventory Up S','Skill Level Up S'],ingredients:['Apple','Ginger','Apple'],settings:catalog.defaults,notes:'Keep this note'};
const upgraded={...base,level:35,subskills:['Skill Trigger M','Helping Speed M',...base.subskills.slice(2)]};
assert.equal(matchesProgression(base,upgraded,catalog),true);
for(const changed of [{nature:'Gentle'},{ingredients:['Apple','Apple','Apple']},{species:'PIKACHU'},{skillLevel:4},{carrySize:33},{subskills:['Helping Speed S','Skill Trigger S',...base.subskills.slice(2)]},{subskills:['Berry Finding S',...base.subskills.slice(1)]},{subskills:['',...base.subskills.slice(1)]}])assert.equal(matchesProgression(base,{...upgraded,...changed},catalog),false);
assert.equal(matchesProgression(upgraded,base,catalog),false,'Subskill downgrades are not upgrades');
const inventoryUpgrade={...upgraded,level:70,carrySize:43,subskills:upgraded.subskills.map(s=>s==='Inventory Up S'?'Inventory Up M':s)};
assert.equal(matchesProgression(upgraded,inventoryUpgrade,catalog),true);
const skillUpgrade={...inventoryUpgrade,level:80,skillLevel:5,subskills:inventoryUpgrade.subskills.map(s=>s==='Skill Level Up S'?'Skill Level Up M':s)};
assert.equal(matchesProgression(inventoryUpgrade,skillUpgrade,catalog),true);
const picture=async()=>{const id=crypto.randomUUID();await savePictures([{id,filename:'test.png',mime:'image/png',blob:new Blob(['test'],{type:'image/png'}),text:[],createdAt:new Date().toISOString()}]);return id};
const oldPic=await picture(),first=await post('/api/pokemon',{build:base,imageIds:[oldPic]});
assert.equal(first.deduplicated,0);
const newPic=await picture(),second=await post('/api/pokemon',{build:upgraded,imageIds:[newPic]});
assert.equal(second.id,first.id);assert.equal(second.deduplicated,1);
assert.equal((await api('/api/pokemon')).length,1);
let row=await api('/api/pokemon/'+first.id);assert.equal(row.historyCount,2);assert.equal(row.analysis.build.level,35);assert.equal(row.screenshots[0].id,newPic);
const db=await database();const read=(store,id)=>new Promise((resolve,reject)=>{const r=db.transaction(store).objectStore(store).get(id);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
assert.equal(await read('screenshots',oldPic),undefined);assert.equal((await read('screenshots',newPic)).owner,first.id);
await post('/api/pokemon',{build:{...upgraded,nickname:'',notes:''}});
row=await api('/api/pokemon/'+first.id);assert.equal(row.analysis.build.nickname,'Sparky');assert.equal(row.analysis.build.notes,'Keep this note');assert.equal(row.screenshots[0].id,newPic);
const concurrent=await Promise.all([post('/api/pokemon',{build:inventoryUpgrade}),post('/api/pokemon',{build:inventoryUpgrade})]);
assert.equal(concurrent[0].id,first.id);assert.equal(concurrent[1].id,first.id);assert.equal((await api('/api/pokemon')).length,1);
const beforeFailure=await read('pokemon',first.id);
await assert.rejects(post('/api/pokemon',{build:skillUpgrade,imageIds:[crypto.randomUUID()]}),/missing/);
assert.deepEqual(await read('pokemon',first.id),beforeFailure,'Invalid screenshots must roll back the entire update');
const unrelatedPic=await picture();const unrelated=await post('/api/pokemon',{build:{...inventoryUpgrade,nature:'Gentle'},imageIds:[unrelatedPic]});
await assert.rejects(post('/api/pokemon',{build:skillUpgrade,imageIds:[unrelatedPic]}),/belongs to another/);
assert.deepEqual(await read('pokemon',first.id),beforeFailure);
assert.equal((await read('screenshots',unrelatedPic)).owner,unrelated.id);
const duplicateIds=[crypto.randomUUID(),crypto.randomUUID()];
await post('/api/restore',{format:'sleep-atlas',version:1,pokemon:duplicateIds.map(id=>({id,build:base,screenshots:[]}))});
const merged=await post('/api/pokemon',{build:skillUpgrade});assert.equal(merged.id,first.id);assert.equal(merged.deduplicated,3);
assert.equal((await api('/api/pokemon')).length,2,'All matching prior entries merge, while the different nature stays separate');
assert.equal((await read('pokemon',first.id)).historyCount,beforeFailure.historyCount+3);
for(const id of duplicateIds)assert.equal(await read('pokemon',id),undefined);
const backup=await api('/api/backup');assert.equal(backup.pokemon.length,2);assert.equal(backup.pokemon.find(p=>p.id===first.id).build.level,80);
assert.equal(Object.hasOwn(backup.pokemon.find(p=>p.id===first.id),'screenshots'),false);
assert.equal((await api('/api/pokemon/'+first.id)).screenshots.length,1);
await api('/api/pokemon/'+first.id,{method:'DELETE'});assert.equal(await read('screenshots',newPic),undefined);
db.close();
console.log('Passed: save without review flag, progression matching, distinct builds, upgrade/unlock bonuses, stable identity, history, screenshot replacement/ownership, atomic failures, concurrent imports, merging existing duplicates, and backup consistency.');
