import assert from 'node:assert/strict';
import fs from 'node:fs';
import {speciesChoices} from '../dist/evolution.js';
const catalog=JSON.parse(fs.readFileSync(new URL('../dist/catalog.json',import.meta.url)));
const names=name=>speciesChoices(catalog,name).map(p=>p.name).sort();
assert.equal(names().length,catalog.species.length,'New entries can select every supported species');
for(const name of ['TREECKO','GROVYLE','SCEPTILE'])assert.deepEqual(names(name),['GROVYLE','SCEPTILE','TREECKO']);
assert.deepEqual(names('GARDEVOIR'),['GALLADE','GARDEVOIR','KIRLIA','RALTS']);
assert.deepEqual(names('SYLVEON'),['EEVEE','ESPEON','FLAREON','GLACEON','JOLTEON','LEAFEON','SYLVEON','UMBREON','VAPOREON']);
assert.deepEqual(names('VULPIX_ALOLAN'),['NINETALES_ALOLAN','VULPIX_ALOLAN']);
assert.deepEqual(names('WOOPER_PALDEAN'),['CLODSIRE','WOOPER_PALDEAN']);
assert.deepEqual(names('PUMPKABOO_SMALL'),['GOURGEIST_SMALL','PUMPKABOO_SMALL']);
for(const name of ['MEW','MEWTWO','PIKACHU_HALLOWEEN'])assert.deepEqual(names(name),[name]);
assert.deepEqual(names('UNKNOWN'),[]);
const partial={species:[{name:'A',displayName:'A',evolvesInto:['B','MISSING']},{name:'B',displayName:'B',evolvesInto:['A']}]};
assert.deepEqual(speciesChoices(partial,'A').map(p=>p.name),['A','B'],'One-sided links and cycles terminate safely');

await import(process.argv[2]);globalThis.fetch=async()=>new Response(JSON.stringify(catalog));
const {api,database,savePictures}=await import('../dist/local-api.js');
const post=body=>api('/api/pokemon',{method:'POST',body:JSON.stringify(body)});
const buildFor=name=>{
  const p=catalog.species.find(p=>p.name===name);
  return {species:name,nickname:p.displayName,level:30,nature:'Hardy',skillLevel:1,carrySize:p.carrySize,subskills:['','','','',''],ingredients:[0,30,60].map(l=>p[`ingredient${l}`][0].ingredient.name),settings:catalog.defaults};
};
const imageId=crypto.randomUUID();
await savePictures([{id:imageId,filename:'test.png',mime:'image/png',blob:new Blob(['test']),text:[],createdAt:new Date().toISOString()}]);
const saved=await post({build:buildFor('TREECKO'),imageIds:[imageId]});
await post({id:saved.id,build:buildFor('SCEPTILE'),imageIds:[imageId]});
const before=await api('/api/pokemon/'+saved.id);
assert.equal(before.analysis.build.species,'SCEPTILE');assert.equal(before.historyCount,2);assert.equal(before.screenshots[0].id,imageId);
await assert.rejects(post({id:saved.id,build:buildFor('DRATINI'),imageIds:[imageId]}),/evolution family/);
assert.deepEqual(await api('/api/pokemon/'+saved.id),before,'Rejected edits must preserve the saved build, history and screenshots');
const newPokemon=await post({build:buildFor('DRATINI')});
assert.notEqual(newPokemon.id,saved.id,'Unrelated species remain available for new entries');
const eevee=await post({build:buildFor('EEVEE')});
await post({id:eevee.id,build:buildFor('SYLVEON')});
await post({id:eevee.id,build:buildFor('JOLTEON')});
assert.equal((await api('/api/pokemon/'+eevee.id)).analysis.build.species,'JOLTEON');
const event=await post({build:buildFor('PIKACHU_HALLOWEEN')});
await assert.rejects(post({id:event.id,build:buildFor('RAICHU')}),/evolution family/);
(await database()).close();
console.log('Passed: unrestricted new entries, evolution families, branches, separate forms, and atomic save validation with history/screenshots preserved.');
