import fs from 'node:fs';
import assert from 'node:assert/strict';
import {parseOCR} from '../dist/ocr-parser.js';
import {Engine} from '../dist/engine.js';
const c=JSON.parse(fs.readFileSync(new URL('../dist/catalog.json',import.meta.url))),fixture=JSON.parse(fs.readFileSync(new URL('mewtwo-ocr-lines.json',import.meta.url)));
const result=parseOCR([fixture],c);
assert.deepEqual(result.fields,{species:'MEWTWO',nature:'Gentle',level:31,skillLevel:6,carrySize:24,displayedFrequencySeconds:1859,subskills:['Helping Speed M','Skill Trigger M','Skill Trigger S','Inventory Up S','Skill Level Up M']});
assert.equal(result.detectedSubskills.length,5);
const partial=parseOCR([{lines:fixture.lines.filter(l=>!l.text.includes('Helping Speed M'))}],c);
assert.equal(partial.fields.subskills[0],'');assert.equal(partial.fields.subskills[1],'Skill Trigger M');
assert.equal(partial.fields.level,31);
const line=(text,x,y)=>({text,x,y,h:.01,confidence:.95});
const combined=parseOCR([{lines:[line('Lv.31 Mewtwo',.2,.1),line('Psystrike (Berry Zone) Lv.6',.25,.4),line('Carry Limit',.1,.3),line('24',.6,.3),line('Gentle',.2,.8),line('Lv.60',.8,.06)]}],c);
assert.equal(combined.fields.species,'MEWTWO');assert.equal(combined.fields.level,31);assert.equal(combined.fields.skillLevel,6);assert.equal(combined.fields.carrySize,24);
assert.equal(parseOCR([{lines:[line('Lv.31 Mew',.2,.1)]}],c).fields.species,'MEW');
assert.equal(parseOCR([{lines:[]}],c).fields.species,undefined);
const engine=new Engine(c),build=engine.validate({...result.fields,ingredients:['Soybean','Soybean','Corn']});
assert.ok(!engine.calculate(build,69).activeSubskills.includes('Inventory Up S'));
assert.ok(engine.calculate(build,70).activeSubskills.includes('Inventory Up S'));
assert.ok(engine.calculate(build,80).activeSubskills.includes('Skill Level Up M'));
console.log('Passed: actual Mewtwo OCR regression, combined headers, nearby carry value, ingredient-level rejection, partial grid safety, name boundaries, and level 70/80 unlocks.');
console.log(JSON.stringify(result.fields));
