import assert from 'node:assert/strict';
import fs from 'node:fs';
import {Engine} from '../dist/engine.js';
import {parseOCR,readDisplayedFrequency} from '../dist/ocr-parser.js';
import {formatFrequency,subskillSlots,withRecordedFrequency} from '../dist/pokemon-stats.js';

const catalog=JSON.parse(fs.readFileSync(new URL('../dist/catalog.json',import.meta.url)));
const fixture=JSON.parse(fs.readFileSync(new URL('mewtwo-ocr-lines.json',import.meta.url)));
const engine=new Engine(catalog),line=(text,x=.4,y=.2)=>({text,x,y,h:.015,confidence:.99});
const read=text=>readDisplayedFrequency([{lines:[line(text)]}]);
for(const [text,seconds] of [['Every 30 mins 59 secs',1859],['Every 28 mins 36 secs',1716],['Every 30 mins 53 secs',1853],['Every 38 mins 37 secs',2317],['Every 45 mins 28 secs',2728],['Every 1 hour 2 mins 3 secs',3723],['Every 0 mins 45 secs',45]])assert.equal(read(text).seconds,seconds);
for(const text of ['Every 30 mins','Every 30 mins 60 secs','Every 0 mins 0 secs','Every 1 hour 70 mins 5 secs','Every 30 mins 20 mins 3 secs','30 mins 53 secs'])assert.equal(read(text).seconds,null,text);
assert.equal(readDisplayedFrequency([{lines:[line('Every 30 mins',.4),line('53 secs',.7),line('29',.4,.3)]}]).seconds,1853);
assert.equal(readDisplayedFrequency([{lines:[line('Every 30 mins',.4),line('Every 30 mins',.401),line('53 secs',.7),line('53 secs',.701)]}]).seconds,1853);
assert.equal(readDisplayedFrequency([{lines:[line('Every 30 mins',.4),line('53 secs',.7,.3)]}]).seconds,null);
assert.deepEqual(readDisplayedFrequency([{lines:[line('Every 30 mins 53 secs')]},{lines:[line('Every 31 mins 0 secs')]}]),{seconds:null,conflict:true});
for(const [seconds,label] of [[1853,'30′53″'],[5551,'92′31″'],[3600,'60′00″'],[1,'0′01″']])assert.equal(formatFrequency(seconds),label);assert.equal(formatFrequency(null),'Not recorded');
const detected=parseOCR([fixture],catalog).fields;
const build=engine.validate({...detected,ingredients:['Soybean','Soybean','Corn']});
const legacy={...build};delete legacy.displayedFrequencySeconds;
const screenshots=[{text:fixture.lines}];
assert.equal(withRecordedFrequency(legacy,screenshots,catalog).displayedFrequencySeconds,1859);
for(const stale of [{...legacy,level:32},{...legacy,nature:'Hardy'},{...legacy,subskills:['Helping Speed S',...legacy.subskills.slice(1)]}])assert.equal(withRecordedFrequency(stale,screenshots,catalog).displayedFrequencySeconds,undefined);
assert.equal(withRecordedFrequency({...legacy,displayedFrequencySeconds:null},screenshots,catalog).displayedFrequencySeconds,null);
assert.deepEqual(subskillSlots(build).map(s=>[s.level,s.name,s.unlocked]),[[10,'Helping Speed M',true],[25,'Skill Trigger M',true],[50,'Skill Trigger S',false],[70,'Inventory Up S',false],[80,'Skill Level Up M',false]]);
assert.deepEqual(subskillSlots({...build,level:70,subskills:['','','','','']}).map(s=>[s.name,s.unlocked]),[['Unknown',true],['Unknown',true],['Unknown',true],['Unknown',true],['Unknown',false]]);
for(const value of [0,-1,1853.2,true,NaN,Infinity,86401,''])assert.throws(()=>engine.validate({...legacy,displayedFrequencySeconds:value}));
assert.equal(engine.validate({...legacy,displayedFrequencySeconds:null}).displayedFrequencySeconds,null);
const without=engine.analyze(legacy),withValue=engine.analyze(build);
for(const key of ['current','forecasts','ingredientAlternatives'])assert.deepEqual(withValue[key],without[key]);

await import(process.argv[2]);globalThis.fetch=async()=>new Response(JSON.stringify(catalog));
const {api,database}=await import('../dist/local-api.js');
const post=(path,body)=>api(path,{method:'POST',body:JSON.stringify(body)});
const id=crypto.randomUUID();
await post('/api/restore',{format:'sleep-atlas',version:1,pokemon:[{id,build:legacy,screenshots:[{filename:'fixture.png',mime:'image/png',data:fs.readFileSync(new URL('ocr-text.png',import.meta.url)).toString('base64'),ocr:{lines:fixture.lines}}]}]});
const row=await api('/api/pokemon/'+id);assert.equal(row.analysis.build.displayedFrequencySeconds,1859);
const backup=await api('/api/backup');assert.equal(backup.pokemon[0].build.displayedFrequencySeconds,1859);assert.equal(Object.hasOwn(backup.pokemon[0],'screenshots'),false);
const updated=await post('/api/pokemon',{build:{...legacy,level:32,displayedFrequencySeconds:1850}});
assert.equal(updated.id,id);assert.equal((await api('/api/pokemon/'+id)).analysis.build.displayedFrequencySeconds,1850);
await post('/api/pokemon',{id,build:{...legacy,level:32},imageIds:row.screenshots.map(p=>p.id)});
assert.equal((await api('/api/pokemon/'+id)).analysis.build.displayedFrequencySeconds,undefined);
await post('/api/pokemon',{id,build:{...legacy,displayedFrequencySeconds:null},imageIds:row.screenshots.map(p=>p.id)});
assert.equal((await api('/api/pokemon/'+id)).analysis.build.displayedFrequencySeconds,null);
(await database()).close();
console.log('Passed: displayed frequency OCR/validation, unchanged modeled output, subskill levels, safe legacy recovery/export, progression updates and explicit clearing.');
