import assert from 'node:assert/strict';
import fs from 'node:fs';
await import(process.argv[2]);
const catalog=fs.readFileSync(new URL('../dist/catalog.json',import.meta.url),'utf8');
globalThis.fetch=async()=>new Response(catalog);
globalThis.FileReader=class {async readAsDataURL(blob){try{this.result='data:'+blob.type+';base64,'+Buffer.from(await blob.arrayBuffer()).toString('base64');this.onload()}catch(e){this.error=e;this.onerror()}}};
const {api,database,savePictures}=await import('../dist/local-api.js');
const build=JSON.parse(fs.readFileSync(new URL('./python-golden.json',import.meta.url)))[0].build;
const post=(path,body)=>api(path,{method:'POST',body:JSON.stringify(body)});
const imageId=crypto.randomUUID();
await savePictures([{id:imageId,filename:'fixture.png',mime:'image/png',blob:new Blob([fs.readFileSync(new URL('ocr-text.png',import.meta.url))],{type:'image/png'}),text:[{text:'Raichu',confidence:.98,x:0,y:0}],createdAt:new Date().toISOString()}]);
await assert.rejects(post('/api/pokemon',{build:{...build,level:0}}));
const {id}=await post('/api/pokemon',{build,imageIds:[imageId]});
assert.equal((await api('/api/pokemon')).length,1);
await post('/api/pokemon',{id,build:{...build,nickname:'Updated'},imageIds:[imageId]});
const row=await api('/api/pokemon/'+id);assert.equal(row.historyCount,2);assert.equal(row.analysis.build.nickname,'Updated');assert.equal(row.screenshots.length,1);
await assert.rejects(post('/api/pokemon',{id,build,imageIds:[crypto.randomUUID()]}));
assert.equal((await api('/api/pokemon/'+id)).historyCount,2);
const backup=await api('/api/backup');assert.equal(backup.pokemon.length,1);assert.ok(backup.pokemon[0].screenshots[0].data.length>100);
assert.deepEqual(await post('/api/restore',backup),{added:0,skipped:1});
const freshId=crypto.randomUUID();
await assert.rejects(post('/api/restore',{...backup,pokemon:[{...backup.pokemon[0],id:freshId},{id:crypto.randomUUID(),build:{}}]}));assert.equal((await api('/api/pokemon')).length,1);
await api('/api/pokemon/'+id,{method:'DELETE'});assert.equal((await api('/api/pokemon')).length,0);
assert.deepEqual(await post('/api/restore',backup),{added:1,skipped:0});
assert.equal((await api('/api/backup')).pokemon[0].screenshots[0].data,backup.pokemon[0].screenshots[0].data);
assert.equal((await api('/api/pokemon/'+id)).analysis.build.nickname,'Updated');
(await database()).close();
console.log('Passed: save/edit, history, screenshot ownership, backup round-trip, duplicate restore, atomic invalid restore, delete and image restore.');
