import assert from 'node:assert/strict';
import fs from 'node:fs';
await import(process.argv[2]);
const catalog=fs.readFileSync(new URL('../dist/catalog.json',import.meta.url),'utf8');
globalThis.fetch=async()=>new Response(catalog);
const {api,database,savePictures}=await import('../dist/local-api.js');
const db=await database();
const build=JSON.parse(fs.readFileSync(new URL('./python-golden.json',import.meta.url)))[0].build;
const post=(path,body)=>api(path,{method:'POST',body:JSON.stringify(body)});
const imageId=crypto.randomUUID();
await savePictures([{id:imageId,filename:'fixture.png',mime:'image/png',blob:new Blob([fs.readFileSync(new URL('ocr-text.png',import.meta.url))],{type:'image/png'}),text:[{text:'Raichu',confidence:.98,x:0,y:0}],createdAt:new Date().toISOString()}]);
await assert.rejects(post('/api/pokemon',{build:{...build,level:0}}));
const {id}=await post('/api/pokemon',{build,imageIds:[imageId]});
assert.equal((await api('/api/pokemon')).length,1);
await post('/api/pokemon',{id,build:{...build,nickname:'Updated',notes:'Keep this helper',displayedFrequencySeconds:1853,settings:{...build.settings,areaBonus:25}},imageIds:[imageId]});
const row=await api('/api/pokemon/'+id);assert.equal(row.historyCount,2);assert.equal(row.analysis.build.nickname,'Updated');assert.equal(row.screenshots.length,1);
await assert.rejects(post('/api/pokemon',{id,build,imageIds:[crypto.randomUUID()]}));
assert.equal((await api('/api/pokemon/'+id)).historyCount,2);
const backup=await api('/api/backup');
assert.deepEqual(backup.pokemon,[{id,build:row.analysis.build}]);
assert.deepEqual((await api('/api/pokemon/'+id)).screenshots,row.screenshots);
const picture=await new Promise((resolve,reject)=>{const r=(db.transaction('screenshots').objectStore('screenshots').get(imageId));r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
assert.deepEqual(Buffer.from(await picture.blob.arrayBuffer()),fs.readFileSync(new URL('ocr-text.png',import.meta.url)));
assert.deepEqual(picture.text,row.screenshots[0].text);
assert.deepEqual(await post('/api/restore',backup),{added:0,updated:0,unchanged:1,skipped:0});
const freshId=crypto.randomUUID();
await assert.rejects(post('/api/restore',{...backup,pokemon:[{...backup.pokemon[0],id:freshId},{id:crypto.randomUUID(),build:{}}]}));assert.equal((await api('/api/pokemon')).length,1);
await api('/api/pokemon/'+id,{method:'DELETE'});assert.equal((await api('/api/pokemon')).length,0);
assert.deepEqual(await post('/api/restore',backup),{added:1,updated:0,unchanged:0,skipped:0});
assert.deepEqual((await api('/api/backup')).pokemon,backup.pokemon);
const restored=await api('/api/pokemon/'+id);
assert.deepEqual(restored.analysis.build,row.analysis.build);
assert.deepEqual(restored.screenshots,[]);
// Older version 1 backups can still restore their embedded screenshots.
await api('/api/pokemon/'+id,{method:'DELETE'});
const legacy={...backup,pokemon:[{...backup.pokemon[0],screenshots:[{filename:picture.filename,mime:picture.mime,data:Buffer.from(await picture.blob.arrayBuffer()).toString('base64'),ocr:{lines:picture.text}}]}]};
assert.deepEqual(await post('/api/restore',legacy),{added:1,updated:0,unchanged:0,skipped:0});
const legacyRow=await api('/api/pokemon/'+id);
assert.equal(legacyRow.screenshots.length,1);
assert.deepEqual(legacyRow.screenshots[0].text,picture.text);
const legacyPicture=await new Promise((resolve,reject)=>{const r=db.transaction('screenshots').objectStore('screenshots').get(legacyRow.screenshots[0].id);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
assert.deepEqual(Buffer.from(await legacyPicture.blob.arrayBuffer()),Buffer.from(await picture.blob.arrayBuffer()));
assert.deepEqual((await api('/api/backup')).pokemon,backup.pokemon);
(await database()).close();
console.log('Passed: save/edit, history, image-free backup round-trip, local screenshot preservation, duplicate/atomic restore, delete and legacy image restore.');
